OPINION_MAP_LAYOUT_CONFIG = {
    "clustering_method": "hdbscan",
    "use_pca_for_clustering": True,
    "pca_components_max": 50,
    "min_cluster_size_ratio": 0.03,
    "min_cluster_size_min": 5,
    "min_samples": 3,
    "umap_neighbors": 8,
    "umap_min_dist": 0.01,
    "umap_spread": 3.0,
    "umap_metric": "cosine",
    "random_state": 42,
    "use_cluster_spacing": True,
    "cluster_spacing_factor": 1.7,
    "noise_cluster_id": -1,
    "noise_cluster_label": "미분류",
    "default_cluster_label": "전체 의견",
    "use_island_layout": False,
}
