OPINION_MAP_LAYOUT_CONFIG = {
    "clustering_method": "hdbscan",
    "use_pca_for_clustering": True,
    "pca_components_max": 50,
    "min_cluster_size_ratio": 0.03,
    "min_cluster_size_min": 5,
    "min_samples": 3,
    "umap_neighbors": 8,
    "umap_min_dist": 0.01,
    "umap_spread": 3.0,
    "umap_metric": "cosine",
    "random_state": 42,
    "use_cluster_spacing": True,
    "cluster_spacing_factor": 1.7,
    "island_anchor_gap": 6.0,
    "island_cluster_radius": 1.15,
    "island_noise_radius": 1.0,
    "reassign_noise_to_nearest_cluster": True,
    "noise_reassignment_threshold": 0.55,
    "noise_cluster_id": -1,
    "noise_cluster_label": "미분류",
    "default_cluster_label": "전체 의견",
    "use_island_layout": True,
    "x_axis_title": "구역 X",
    "y_axis_title": "구역 Y",
    "x_axis_description": "좌우 위치는 군집 구역을 분리하기 위한 표시 좌표이며 찬성/반대 같은 고정 의미가 아닙니다.",
    "y_axis_description": "상하 위치는 군집 구역을 분리하기 위한 표시 좌표이며 중요도/강도 같은 고정 의미가 아닙니다.",
    "coordinate_note": "baseX/baseY는 UMAP 원본 좌표이고 x/y는 구역 분리를 위해 보정된 최종 표시 좌표입니다.",
    "legend_title": "군집 범례",
    "legend_description": "색상은 최종 군집을 의미하고 회색은 가까운 군집으로 흡수되지 않은 미분류 의견입니다.",
}
